
version: '3.9'
services:
  server:
    build: ./server
    environment:
      - PORT=8080
      - HL_ADDR_FOR_PROBING=0xYOUR_HL_ADDR
    ports:
      - '8080:8080'

  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
    ports:
      - '3000:3000'
    depends_on:
      - server
