
version: '3.9'
services:
  server:
    build: ./server
    environment:
      - PORT=8080
      - NODE_ENV=production
    expose:
      - '8080'
    restart: unless-stopped

  web:
    build:
      context: ./web
    environment:
      - NEXT_PUBLIC_WS_URL=wss://your.domain/ws
      - NODE_ENV=production
    command: sh -c "npm run build && npm start -p 3000 || (yarn build && yarn start -p 3000)"
    expose:
      - '3000'
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - server
      - web
    restart: unless-stopped
